// World Trotter visual style: editable-feeling itinerary builder using local visual state only.
import { ArrowRight, Plus, Route } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";
import AppShell from "@/components/layout/AppShell";
import PageIntro from "@/components/shared/PageIntro";
import ItineraryDayBlock from "@/components/itinerary/ItineraryDayBlock";
import { itineraryDays } from "@/lib/presentationData";
export default function ItineraryBuilderPage() { const [extra, setExtra] = useState(0); const [, navigate] = useLocation(); const displayed = [...itineraryDays, ...Array.from({ length: extra }, (_, index) => ({ day: `Day ${String(index + 4).padStart(2, "0")}`, date: `${21 + index} Sep`, city: "Lagos", theme: "A day with room to wander", items: ["Beach morning", "Market lunch", "Sunset walk"], cost: "€96" }))]; return <AppShell><section className="mx-auto max-w-[1120px] px-5 py-12 lg:px-8"><PageIntro eyebrow="Step 02 · shape the days" title={<>Build a rhythm you want to remember<span className="text-[var(--gold)]">.</span></>} description="Arrange your stops one day at a time. This frontend preview uses local presentation content; saving will be added with the backend." action={<button onClick={() => setExtra(value => value + 1)} className="inline-flex items-center gap-2 rounded-full border border-[var(--line)] bg-white px-5 py-3 text-sm font-extrabold text-[var(--navy)]"><Plus size={16}/>Add a day</button>}/><div className="mt-10 grid gap-7 lg:grid-cols-[1fr_300px]"><div className="space-y-4">{displayed.map((entry, index) => <ItineraryDayBlock key={`${entry.day}-${index}`} entry={entry} index={index}/>)}</div><aside className="self-start rounded-[26px] bg-[var(--navy)] p-6 text-white"><Route className="text-[var(--gold)]"/><p className="mt-5 text-[10px] font-black uppercase tracking-[.18em] text-white/60">Route at a glance</p><h2 className="mt-2 font-serif text-3xl font-bold">Lisbon to Lagos</h2><p className="mt-3 text-sm leading-6 text-white/70">3 cities · 10 unhurried days · a route made for long lunches and sea air.</p><button onClick={() => navigate("/itinerary-view")} className="mt-7 inline-flex items-center gap-2 rounded-full bg-[var(--gold)] px-5 py-3 text-sm font-extrabold text-[var(--navy)]">Review the itinerary <ArrowRight size={16}/></button></aside></div></section></AppShell>; }
