// World Trotter visual style: soft, readable budget breakdown for planning with confidence.
import { ArrowRight, CircleDollarSign } from "lucide-react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "wouter";
import AppShell from "@/components/layout/AppShell";
import PageIntro from "@/components/shared/PageIntro";
import BudgetSummary from "@/components/itinerary/BudgetSummary";
import { budgetData } from "@/lib/presentationData";
export default function TripBudgetPage() { return <AppShell><section className="mx-auto max-w-[1120px] px-5 py-12 lg:px-8"><PageIntro eyebrow="Stay comfortable with the numbers" title={<>Budget, without the busywork<span className="text-[var(--gold)]">.</span></>} description="A clear read on where your travel money is going, so the good decisions stay easy." action={<Link href="/itinerary-view" className="inline-flex items-center gap-2 rounded-full border border-[var(--line)] bg-white px-5 py-3 text-sm font-extrabold text-[var(--navy)]">Back to route <ArrowRight size={15}/></Link>}/><div className="mt-10 grid gap-7 lg:grid-cols-[.85fr_1.15fr]"><BudgetSummary/><div className="rounded-[26px] border border-[var(--line)] bg-white p-6"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[var(--gold)]">Estimated spend</p><h2 className="mt-2 font-serif text-3xl font-bold text-[var(--navy)]">What the route is asking for</h2><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={budgetData}><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#6f7c80", fontSize: 11 }}/><YAxis hide/><Tooltip cursor={{ fill: "#f5efe6" }}/><Bar dataKey="value" radius={[8,8,0,0]}>{budgetData.map(item => <Cell key={item.label} fill={item.color}/>)}</Bar></BarChart></ResponsiveContainer></div></div></div><div className="mt-7 rounded-[26px] border border-[var(--line)] bg-white p-6"><div className="grid items-center gap-5 md:grid-cols-[.55fr_1fr]"><div className="h-44"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={budgetData} dataKey="value" innerRadius={44} outerRadius={70} paddingAngle={4}>{budgetData.map(item => <Cell key={item.label} fill={item.color}/>)}</Pie></PieChart></ResponsiveContainer></div><div><p className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.18em] text-[var(--gold)]"><CircleDollarSign size={14}/>A gentle check-in</p><h2 className="mt-2 font-serif text-3xl font-bold text-[var(--navy)]">You still have room for a beautiful detour.</h2><p className="mt-3 text-sm leading-6 text-[var(--ink-muted)]">At the current pace, €210 remains available for an extra meal, a spontaneous ticket, or something you have not seen coming yet.</p></div></div></div></section></AppShell>; }
