import type { RequestHandler } from "express";
import { Comment } from "../models/Comment.model";
import { CommunityPost } from "../models/CommunityPost.model";
import { Like } from "../models/Like.model";
import { ApiError, ok } from "../utils/apiResponse";
import { getPagination, pageMeta } from "../utils/pagination";
import { getListQuery } from "../utils/queryFilters";

async function ownedPost(id: string, userId: string, role: string) { const post = await CommunityPost.findById(id); if (!post) throw new ApiError(404, "Community post not found"); if (String(post.author) !== userId && role !== "admin") throw new ApiError(403, "You can only manage your own posts"); return post; }
export const createPost: RequestHandler = async (req, res) => { const post = await CommunityPost.create({ ...req.body, author: req.user!.id }); res.status(201).json(ok(post, "Community post published")); };
export const listPosts: RequestHandler = async (req, res) => { const { page, limit, skip } = getPagination(req); const { mongoQuery, sort } = getListQuery(req.query, ["title", "content", "destination", "country", "tags"]); if (req.query.sortBy === "mostLiked") Object.assign(sort, { likesCount: -1 }); const [items, total] = await Promise.all([CommunityPost.find(mongoQuery).sort(sort).skip(skip).limit(limit).populate("author", "firstName lastName avatarUrl").populate("trip", "title").populate("activity", "name"), CommunityPost.countDocuments(mongoQuery)]); res.json(ok({ items, pagination: pageMeta(page, limit, total) })); };
export const getPost: RequestHandler = async (req, res) => { const post = await CommunityPost.findById(req.params.id).populate("author", "firstName lastName avatarUrl").populate("trip", "title"); if (!post) throw new ApiError(404, "Community post not found"); res.json(ok(post)); };
export const updatePost: RequestHandler = async (req, res) => { const post = await ownedPost(req.params.id, req.user!.id, req.user!.role); Object.assign(post, req.body); await post.save(); res.json(ok(post, "Community post updated")); };
export const deletePost: RequestHandler = async (req, res) => { const post = await ownedPost(req.params.id, req.user!.id, req.user!.role); await Promise.all([Comment.deleteMany({ post: post.id }), Like.deleteMany({ post: post.id }), post.deleteOne()]); res.json(ok({ deleted: true }, "Community post deleted")); };
export const likePost: RequestHandler = async (req, res) => { const post = await CommunityPost.findById(req.params.id); if (!post) throw new ApiError(404, "Community post not found"); const like = await Like.findOne({ post: post.id, user: req.user!.id }); let liked: boolean; if (like) { await like.deleteOne(); post.likesCount = Math.max(0, post.likesCount - 1); liked = false; } else { await Like.create({ post: post.id, user: req.user!.id }); post.likesCount += 1; liked = true; } await post.save(); res.json(ok({ liked, likesCount: post.likesCount }, liked ? "Post liked" : "Like removed")); };
export const listComments: RequestHandler = async (req, res) => { const comments = await Comment.find({ post: req.params.id }).sort({ createdAt: 1 }).populate("author", "firstName lastName avatarUrl"); res.json(ok(comments)); };
export const createComment: RequestHandler = async (req, res) => { const post = await CommunityPost.findById(req.params.id); if (!post) throw new ApiError(404, "Community post not found"); const comment = await Comment.create({ post: post.id, author: req.user!.id, content: req.body.content }); post.commentsCount += 1; await post.save(); res.status(201).json(ok(await comment.populate("author", "firstName lastName avatarUrl"), "Comment added")); };
export const updateComment: RequestHandler = async (req, res) => { const comment = await Comment.findById(req.params.id); if (!comment) throw new ApiError(404, "Comment not found"); if (String(comment.author) !== req.user!.id && req.user!.role !== "admin") throw new ApiError(403, "You can only manage your own comments"); comment.content = req.body.content; await comment.save(); res.json(ok(comment, "Comment updated")); };
export const deleteComment: RequestHandler = async (req, res) => { const comment = await Comment.findById(req.params.id); if (!comment) throw new ApiError(404, "Comment not found"); if (String(comment.author) !== req.user!.id && req.user!.role !== "admin") throw new ApiError(403, "You can only manage your own comments"); await Promise.all([CommunityPost.updateOne({ _id: comment.post }, { $inc: { commentsCount: -1 } }), comment.deleteOne()]); res.json(ok({ deleted: true }, "Comment deleted")); };
