import type { RequestHandler } from "express";
import { ItineraryActivity } from "../models/ItineraryActivity.model";
import { SharedTrip } from "../models/SharedTrip.model";
import { Trip } from "../models/Trip.model";
import { TripSection } from "../models/TripSection.model";
import { ApiError, ok } from "../utils/apiResponse";

async function publicTrip(token: string) { const shared = await SharedTrip.findOne({ shareToken: token, isPublic: true }).populate("trip"); if (!shared || !shared.trip) throw new ApiError(404, "Shared trip not found"); return shared; }
export const getSharedTrip: RequestHandler = async (req, res) => { const shared = await publicTrip(req.params.shareToken); shared.viewCount += 1; await shared.save(); const trip = shared.trip as any; const sections = await TripSection.find({ trip: trip.id }).sort({ orderIndex: 1 }); const activities = await ItineraryActivity.find({ tripSection: { $in: sections.map(section => section.id) } }).sort({ orderIndex: 1 }); res.json(ok({ trip, sections: sections.map(section => ({ ...section.toJSON(), activities: activities.filter(activity => String(activity.tripSection) === section.id) })), viewCount: shared.viewCount })); };
export const copySharedTrip: RequestHandler = async (req, res) => { const shared = await publicTrip(req.params.shareToken); const source = shared.trip as any; const copy = await Trip.create({ ...source.toObject(), _id: undefined, id: undefined, owner: req.user!.id, title: `${source.title} (copy)`, isPublic: false, createdAt: undefined, updatedAt: undefined }); const sections = await TripSection.find({ trip: source.id }).sort({ orderIndex: 1 }); for (const section of sections) { const cloned = await TripSection.create({ ...section.toObject(), _id: undefined, id: undefined, trip: copy.id, createdAt: undefined, updatedAt: undefined }); const activities = await ItineraryActivity.find({ tripSection: section.id }); await ItineraryActivity.insertMany(activities.map(activity => ({ ...activity.toObject(), _id: undefined, id: undefined, tripSection: cloned.id, createdAt: undefined, updatedAt: undefined }))); } res.status(201).json(ok(copy, "Shared trip copied to your journal")); };
