import type { RequestHandler } from "express";
import { nanoid } from "nanoid";
import { Expense } from "../models/Expense.model";
import { ItineraryActivity } from "../models/ItineraryActivity.model";
import { SharedTrip } from "../models/SharedTrip.model";
import { Trip } from "../models/Trip.model";
import { TripSection } from "../models/TripSection.model";
import { storagePut } from "../storage";
import { ApiError, ok } from "../utils/apiResponse";
import { getPagination, pageMeta } from "../utils/pagination";
import { getListQuery } from "../utils/queryFilters";

async function ownedTrip(id: string, userId: string) { const trip = await Trip.findById(id); if (!trip) throw new ApiError(404, "Trip not found"); if (String(trip.owner) !== userId) throw new ApiError(403, "You do not have access to this trip"); return trip; }
async function ownedSection(tripId: string, sectionId: string, userId: string) { await ownedTrip(tripId, userId); const section = await TripSection.findOne({ _id: sectionId, trip: tripId }); if (!section) throw new ApiError(404, "Itinerary section not found"); return section; }

export const createTrip: RequestHandler = async (req, res) => { const trip = await Trip.create({ ...req.body, owner: req.user!.id }); res.status(201).json(ok(trip, "Trip created")); };
export const listTrips: RequestHandler = async (req, res) => { const { page, limit, skip } = getPagination(req); const { mongoQuery, sort, groupBy } = getListQuery(req.query, ["title", "description", "destinations.city"]); mongoQuery.owner = req.user!.id; if (groupBy) { const groups = await Trip.aggregate([{ $match: mongoQuery }, { $group: { _id: `$${groupBy}`, items: { $push: "$$ROOT" } } }]); return res.json(ok({ groups })); } const [items, total] = await Promise.all([Trip.find(mongoQuery).sort(sort).skip(skip).limit(limit), Trip.countDocuments(mongoQuery)]); res.json(ok({ items, pagination: pageMeta(page, limit, total) })); };
export const getTrip: RequestHandler = async (req, res) => { const trip = await ownedTrip(req.params.id, req.user!.id); const sections = await TripSection.find({ trip: trip.id }).sort({ orderIndex: 1 }); const activities = await ItineraryActivity.find({ tripSection: { $in: sections.map(section => section.id) } }).sort({ orderIndex: 1 }); res.json(ok({ trip, sections: sections.map(section => ({ ...section.toJSON(), activities: activities.filter(activity => String(activity.tripSection) === section.id) })) })); };
export const updateTrip: RequestHandler = async (req, res) => { const trip = await ownedTrip(req.params.id, req.user!.id); Object.assign(trip, req.body); await trip.save(); res.json(ok(trip, "Trip updated")); };
export const deleteTrip: RequestHandler = async (req, res) => { const trip = await ownedTrip(req.params.id, req.user!.id); const sections = await TripSection.find({ trip: trip.id }); await Promise.all([ItineraryActivity.deleteMany({ tripSection: { $in: sections.map(section => section.id) } }), TripSection.deleteMany({ trip: trip.id }), Expense.deleteMany({ trip: trip.id }), SharedTrip.deleteOne({ trip: trip.id }), trip.deleteOne()]); res.json(ok({ deleted: true }, "Trip deleted")); };
export const duplicateTrip: RequestHandler = async (req, res) => { const source = await ownedTrip(req.params.id, req.user!.id); const copy = await Trip.create({ ...source.toObject(), _id: undefined, id: undefined, title: `${source.title} (copy)`, owner: req.user!.id, createdAt: undefined, updatedAt: undefined }); const sections = await TripSection.find({ trip: source.id }).sort({ orderIndex: 1 }); for (const section of sections) { const cloned = await TripSection.create({ ...section.toObject(), _id: undefined, id: undefined, trip: copy.id, createdAt: undefined, updatedAt: undefined }); const activities = await ItineraryActivity.find({ tripSection: section.id }); await ItineraryActivity.insertMany(activities.map(activity => ({ ...activity.toObject(), _id: undefined, id: undefined, tripSection: cloned.id, createdAt: undefined, updatedAt: undefined }))); } res.status(201).json(ok(copy, "Trip duplicated")); };
export const uploadCover: RequestHandler = async (req, res) => { const trip = await ownedTrip(req.params.id, req.user!.id); if (!req.file) throw new ApiError(422, "An image is required"); const asset = await storagePut(`trips/${trip.id}/cover-${req.file.originalname}`, req.file.buffer, req.file.mimetype); trip.coverImageUrl = asset.url; trip.coverImageKey = asset.key; await trip.save(); res.json(ok(trip, "Trip cover updated")); };
export const createSection: RequestHandler = async (req, res) => { await ownedTrip(req.params.tripId, req.user!.id); const highest = await TripSection.findOne({ trip: req.params.tripId }).sort({ orderIndex: -1 }); const section = await TripSection.create({ ...req.body, trip: req.params.tripId, orderIndex: req.body.orderIndex ?? (highest?.orderIndex ?? -1) + 1 }); res.status(201).json(ok(section, "Itinerary section created")); };
export const listSections: RequestHandler = async (req, res) => { await ownedTrip(req.params.tripId, req.user!.id); const sections = await TripSection.find({ trip: req.params.tripId }).sort({ orderIndex: 1 }); res.json(ok(sections)); };
export const updateSection: RequestHandler = async (req, res) => { const section = await ownedSection(req.params.tripId, req.params.sectionId, req.user!.id); Object.assign(section, req.body); await section.save(); res.json(ok(section, "Itinerary section updated")); };
export const deleteSection: RequestHandler = async (req, res) => { const section = await ownedSection(req.params.tripId, req.params.sectionId, req.user!.id); await Promise.all([ItineraryActivity.deleteMany({ tripSection: section.id }), section.deleteOne()]); res.json(ok({ deleted: true }, "Itinerary section deleted")); };
export const duplicateSection: RequestHandler = async (req, res) => { const section = await ownedSection(req.params.tripId, req.params.sectionId, req.user!.id); const duplicate = await TripSection.create({ ...section.toObject(), _id: undefined, id: undefined, title: `${section.title ?? section.city} (copy)`, orderIndex: section.orderIndex + .5, createdAt: undefined, updatedAt: undefined }); const activities = await ItineraryActivity.find({ tripSection: section.id }); await ItineraryActivity.insertMany(activities.map(activity => ({ ...activity.toObject(), _id: undefined, id: undefined, tripSection: duplicate.id, createdAt: undefined, updatedAt: undefined }))); res.status(201).json(ok(duplicate, "Itinerary section duplicated")); };
export const reorderSections: RequestHandler = async (req, res) => { await ownedTrip(req.params.tripId, req.user!.id); const ids = req.body.sectionIds as string[]; if (!Array.isArray(ids)) throw new ApiError(422, "sectionIds must be an array"); await Promise.all(ids.map((id, orderIndex) => TripSection.updateOne({ _id: id, trip: req.params.tripId }, { orderIndex }))); res.json(ok({ sectionIds: ids }, "Itinerary sections reordered")); };
export const createItineraryActivity: RequestHandler = async (req, res) => { const section = await ownedSection(req.params.tripId, req.params.sectionId, req.user!.id); const highest = await ItineraryActivity.findOne({ tripSection: section.id }).sort({ orderIndex: -1 }); const activity = await ItineraryActivity.create({ ...req.body, tripSection: section.id, orderIndex: req.body.orderIndex ?? (highest?.orderIndex ?? -1) + 1 }); res.status(201).json(ok(activity, "Itinerary activity added")); };
export const listItineraryActivities: RequestHandler = async (req, res) => { const section = await ownedSection(req.params.tripId, req.params.sectionId, req.user!.id); res.json(ok(await ItineraryActivity.find({ tripSection: section.id }).sort({ orderIndex: 1 }))); };
export const updateItineraryActivity: RequestHandler = async (req, res) => { await ownedSection(req.params.tripId, req.params.sectionId, req.user!.id); const activity = await ItineraryActivity.findOneAndUpdate({ _id: req.params.activityId, tripSection: req.params.sectionId }, req.body, { new: true, runValidators: true }); if (!activity) throw new ApiError(404, "Itinerary activity not found"); res.json(ok(activity, "Itinerary activity updated")); };
export const deleteItineraryActivity: RequestHandler = async (req, res) => { await ownedSection(req.params.tripId, req.params.sectionId, req.user!.id); await ItineraryActivity.findOneAndDelete({ _id: req.params.activityId, tripSection: req.params.sectionId }); res.json(ok({ deleted: true }, "Itinerary activity deleted")); };
export const reorderItineraryActivities: RequestHandler = async (req, res) => { await ownedSection(req.params.tripId, req.params.sectionId, req.user!.id); const ids = req.body.activityIds as string[]; if (!Array.isArray(ids)) throw new ApiError(422, "activityIds must be an array"); await Promise.all(ids.map((id, orderIndex) => ItineraryActivity.updateOne({ _id: id, tripSection: req.params.sectionId }, { orderIndex }))); res.json(ok({ activityIds: ids }, "Itinerary activities reordered")); };
export const getBudget: RequestHandler = async (req, res) => { const trip = await ownedTrip(req.params.tripId, req.user!.id); const sections = await TripSection.find({ trip: trip.id }); const activities = await ItineraryActivity.find({ tripSection: { $in: sections.map(section => section.id) } }); const expenses = await Expense.find({ trip: trip.id }); const breakdown = { stay: 0, transport: 0, food: 0, activities: 0, other: 0 }; for (const item of expenses) breakdown[item.category as keyof typeof breakdown] += item.amount; for (const activity of activities) breakdown.activities += activity.cost; const estimatedSpend = Object.values(breakdown).reduce((sum, value) => sum + value, 0); const remaining = Math.max(0, trip.budget - estimatedSpend); res.json(ok({ totalBudget: trip.budget, estimatedSpend, remaining, categoryBreakdown: breakdown, dailySpending: expenses.map(expense => ({ date: expense.date, amount: expense.amount })), status: estimatedSpend > trip.budget ? "over_budget" : estimatedSpend >= trip.budget * .85 ? "near_limit" : "under_budget" })); };
export const createExpense: RequestHandler = async (req, res) => { await ownedTrip(req.params.tripId, req.user!.id); const expense = await Expense.create({ ...req.body, trip: req.params.tripId }); res.status(201).json(ok(expense, "Expense added")); };
export const listExpenses: RequestHandler = async (req, res) => { await ownedTrip(req.params.tripId, req.user!.id); res.json(ok(await Expense.find({ trip: req.params.tripId }).sort({ date: -1, createdAt: -1 }))); };
export const updateExpense: RequestHandler = async (req, res) => { await ownedTrip(req.params.tripId, req.user!.id); const expense = await Expense.findOneAndUpdate({ _id: req.params.id, trip: req.params.tripId }, req.body, { new: true, runValidators: true }); if (!expense) throw new ApiError(404, "Expense not found"); res.json(ok(expense, "Expense updated")); };
export const deleteExpense: RequestHandler = async (req, res) => { await ownedTrip(req.params.tripId, req.user!.id); await Expense.findOneAndDelete({ _id: req.params.id, trip: req.params.tripId }); res.json(ok({ deleted: true }, "Expense deleted")); };
export const getCalendar: RequestHandler = async (req, res) => { const month = Number(req.query.month); const year = Number(req.query.year); if (!month || !year) throw new ApiError(422, "month and year are required"); const from = new Date(Date.UTC(year, month - 1, 1)); const to = new Date(Date.UTC(year, month, 1)); const trips = await Trip.find({ owner: req.user!.id, startDate: { $lt: to }, endDate: { $gte: from } }); res.json(ok(trips.map(trip => ({ id: trip.id, title: trip.title, startDate: trip.startDate, endDate: trip.endDate, status: trip.status, type: "trip" })))); };
export const createShare: RequestHandler = async (req, res) => { const trip = await ownedTrip(req.params.tripId, req.user!.id); const shared = await SharedTrip.findOneAndUpdate({ trip: trip.id }, { trip: trip.id, shareToken: nanoid(12), isPublic: true }, { new: true, upsert: true }); res.status(201).json(ok({ shareToken: shared.shareToken, url: `/shared/${shared.shareToken}` }, "Trip shared")); };
export const deleteShare: RequestHandler = async (req, res) => { const trip = await ownedTrip(req.params.tripId, req.user!.id); await SharedTrip.deleteOne({ trip: trip.id }); res.json(ok({ deleted: true }, "Public sharing removed")); };
